"""Added file processing status column

Revision ID: 5d6fe3e30cbd
Revises: a1c956f6f9f3
Create Date: 2025-11-26 15:16:51.792240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6fe3e30cbd'
down_revision: Union[str, None] = 'a1c956f6f9f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
