"""Added docs retrieval for source list

Revision ID: a1c956f6f9f3
Revises: 32e778e7bd37
Create Date: 2025-11-25 12:52:58.300669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1c956f6f9f3'
down_revision: Union[str, None] = '32e778e7bd37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('retrieved_docs', sa.JSON(), nullable=True))
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_sessions', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('chat_messages', 'retrieved_docs')
    # ### end Alembic commands ###
